name: API

defaults:
  run:
    working-directory: api

on:
  push:
    paths:
      - api/**

env:
  ECR_REPOSITORY: solmines-ecr-repository
  ECS_CLUSTER: solmines-ecs-cluster
  ECS_SERVICE: solmines-ecs-service
  ECS_TASK_DEFINITION: solmines-ecs-task-definition
  CONTAINER_NAME: solmines

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v3
        with:
          build-args:
            - "mongodb_uri=${{ secrets.MONGODB_URI }}"
            - "secret_key=${{ secrets.SECRET_KEY }}"
          context: .
          push: true
          tags: latest
